function startup()
% startup.m - Initializes the MATLAB path for the Digital Twin project
% Automatically generated by Antigravity sanitization workflow.

% Get the absolute path of the directory containing this script
rootPath = fileparts(mfilename('fullpath'));

% Define the target subdirectories to add to path
folders = {'src', 'app', 'config', 'data'};

% Add each folder to the path
for i = 1:length(folders)
    folderPath = fullfile(rootPath, folders{i});
    if isfolder(folderPath)
        addpath(folderPath);
        fprintf('Added to path: %s\n', folderPath);
    else
        warning('Folder not found: %s', folderPath);
    end
end

fprintf('Digital Twin Environment Initialized.\n');
end
