PROMPTS = {
    "precision-audit": {
        "name": "precision-audit",
        "description": "Audit theory, Monte Carlo validation, and bootstrap confidence intervals for the active precision sweep.",
        "template": (
            "You are controlling the HILIGHTer Digital Twin through MCP. "
            "Start by reading backend status, current config, and GUI schema. "
            "Run the precision workflow. "
            "Compare ideal, theory, and Monte Carlo outputs. "
            "Treat the ideal reference as the histogram-bin theoretical ceiling even if the active configuration uses sequential gating. "
            "If confidence intervals are present, use them instead of pointwise Monte Carlo values. "
            "Treat photon efficiency as physically capped at 1. "
            "Explicitly report regions where Monte Carlo compatibility is false at the configured estimator-accuracy threshold, "
            "and distinguish theory-only conclusions from statistically validated conclusions."
        ),
    },
    "instrument-design": {
        "name": "instrument-design",
        "description": "Design or refine an excitation, detection, and gating architecture for a target lifetime regime.",
        "template": (
            "Use the Digital Twin as an instrument-design copilot. "
            "Inspect the current configuration, GUI schema, and diagnostics. "
            "Identify the active target parameter and propose a sweep plan spanning excitation, detection, and gate settings. "
            "Run precision analysis, compare theory and Monte Carlo, and recommend the most robust design. "
            "Prioritize configurations that improve F-value while preserving Monte Carlo compatibility. "
            "If sequential gating or explicit overlap are involved, mention that these modes are still under development."
        ),
    },
    "data-inspection": {
        "name": "data-inspection",
        "description": "Inspect simulated data products, maps, diagnostics, and representative pixels.",
        "template": (
            "Use the Digital Twin data interfaces to inspect the current simulated state. "
            "Retrieve the data summary, full results snapshot, tau map, phasor map, theory locus, diagnostics snapshot, and one representative pixel analysis. "
            "Explain what these artifacts say about estimator behavior, instrument performance, and likely failure modes. "
            "If a diagnostics PDF ensemble is present, interpret it as the family of PDFs generated by sweeping the active X-axis parameter."
        ),
    },
    "workspace-navigation": {
        "name": "workspace-navigation",
        "description": "Guide a user or agent through the desktop workspace using the GUI schema and action identifiers.",
        "template": (
            "Use the GUI schema as the source of truth for the desktop workspace. "
            "When referencing controls, name the controller tab, action button, or plot region explicitly by its schema label and identifier. "
            "When proposing a workflow, map each step to concrete GUI elements such as RUN, EXPORT, TEST, or the Precision and Diagnostics widgets."
        ),
    },
    "instrument-profile-builder": {
        "name": "instrument-profile-builder",
        "description": "Use vendor documentation and MCP tools to build a new instrument-definition JSON with explicit confirmation of missing specs.",
        "template": (
            "Use the HILIGHTer MCP to create an instrument profile from vendor documentation. "
            "Start by reading the instrument-profile schema and the vendors-info index. "
            "Read the relevant vendor documents, then call draft_instrument_profile with the selected source files and component names. "
            "Treat missing_or_unconfirmed_specs as questions that must be asked to the user. "
            "If the vendor documents do not specify a parameter, identify a common or conservative default, present it clearly as an assumption, and ask the user to confirm it. "
            "After the user confirms the missing items, call finalize_instrument_profile with the completed profile JSON or config patch. "
            "Do not silently invent hardware specifications. Record confirmed assumptions in metadata."
        ),
    },
    "optimisation-loop": {
        "name": "optimisation-loop",
        "description": "Run and review the integrated detection, excitation, or joint optimisation workflow.",
        "template": (
            "Use the Digital Twin optimisation surfaces to inspect the current controller state, verify which optimisation targets are enabled, "
            "and run the implemented optimisation workflow. "
            "Identify which detection strategy is selected: Fisher Compression, Direct Mean F Minimisation, Partition Theorem Bottom-Up, or Partition Theorem Top-Down, "
            "and which excitation strategy is selected: Gaussian, Square, or Free Form. "
            "Summarise the objective-history trend, the minimum-F history, the retained intermediate states, and whether post-run Monte Carlo validation was requested. "
            "If Fisher Compression auto-compress is enabled, interpret the stopping criterion as an absolute peak F^-2 loss measured against the initial finer optimised partition. "
            "If Fisher-throughput mode is enabled, report the configured Max F^-2 Loss (%), explain that it is an absolute peak-efficiency loss budget in percentage points, "
            "and describe whether throughput gains came from reduced gate count, changed information efficiency, increased excitation area under fixed-peak mode, or a combination of these. "
            "If excitation optimisation was active, report the final excitation-profile summary including profile family, constraint, equivalent width, and the final width or free-form control points. "
            "If nuisance-aware Fisher Compression is enabled, interpret the compression score as a Schur-complement effective Fisher metric with the active unfixed nuisance parameters."
        ),
    },
}


def get_prompts():
    return PROMPTS
