% BH_CUMHIST
LT={};
HS={};
folder_name = uigetdir(cd,'Select folder containing the histrograms generated by SPCImage');
cd(folder_name)
%%
Files = dir([folder_name  '\*.txt']);
n_files=length(Files);
for i=1:n_files               % flow control: cycle to read all the files
    fid = fopen([folder_name '/' Files(i).name],'r');
        res = textscan(fid, '%f %f');
        LT{i} = res{1};
        HS{i} = res{2};
    fclose(fid);
end

% add checks on LT

x = [LT{1}];
y = [HS{:}]./repmat(sum([HS{:}],1),[101 1]);
y_pdf = sum(y,2)/size(y,2);
y_cdf = cumsum(y_pdf);
figure,plot(x,y)
figure,plot(x,y_pdf)
figure,plot(x,y_cdf)

x(min(find(y_cdf>0.5)))

save BH_CUMHIST.mat x y y_pdf y_cdf 

%%


folders = {'20080616_NSP5EGFP', '20080808_Winsome', '20080813_Winsome'};

xc=[];
yc_pdf=[];
ycf_pdf=[];
yc_cdf=[];
avg = {};
for i=4:4
(i-round(i/2))
    if (i-2*round(i/2))==0
        folder_name=['C:\DATA\Collaborators\Winsome\' folders{floor((i-1)/2)+1} '\export\control\'];
    else
        folder_name=['C:\DATA\Collaborators\Winsome\' folders{floor((i-1)/2)+1} '\export\fret\'];
    end
    file_name = 'BH_CUMHIST.mat';

folder_name;
%    [file_name folder_name] = uigetfile('BH_CUMHIST.mat');
    eval(['load ' folder_name file_name])
    yc_pdf(i,:)=y_pdf';
    yc_cdf(i,:)=y_cdf';    
    x(min(find(y_cdf>0.5)));
    
    for j=1:size(y,2)
       avg{i}(j) = x(min(find(cumsum(y(:,j))>=0.5)))
    end
sm=15;

yf = circshift(filter(ones([1 sm]),[1/sm],y),round(-sm/2));
yf_pdf = sum(yf,2)/size(yf,2);
figure,plot(x,yf_pdf)
title(num2str(i))
figure,plot(x,yf)
title(num2str(i))

end

figure,plot(x,yc_cdf')

% p/cdf_iiexp_control_noutlier_6.eps
% figure,cdf=sum(yf(:,[1 2 3 4 5 7 8]),2);plot(x,cdf/sum(cdf))
% figure,cdf=sum(yf(:,[1 2 3 4 5 7 8]),2);plot(x,cumsum(cdf/sum(cdf)))
% histo: figure,plot(x,yf./repmat(sum(yf),[101 1]))

% p/cdf_iiexp_fret_noutlier_9_18.eps
% figure,cdf=sum(yf(:,[1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17]),2);plot(x,cdf/sum(cdf))
% figure,cdf=sum(yf(:,[1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17]),2);plot(x,cumsum(cdf/sum(cdf)))
% histo: figure,plot(x,yf./repmat(sum(yf),[101 1]))